### ISSUE TITLE
How to Use Package in Project?

### ISSUE THREAD

**Issue by GokulReddy** [larsyencken/csvdiff#8]
I found this package to be too good for the folks who deal with the files. I loved it. But the difficulty which i am facing it is how to use this package in my project? instead of running from the terminal?
csvdiff --style=summary id a.csv b.csv   -- I dont want to use like this

It would be great helpfull if you help me in executing the package in way which i specified below..
import csvdiff
csvdiff.csvdiff_cmd(id,a.csv,b.csv,--style="summary")

I should execute this package in another .py file

**Comment by larsyencken** [comment]
You can do something like this:

```
import csvdiff
diff = csvdiff.diff_files('a.csv', b.csv', ['id'])
```

Now `diff` is the full JSON patch record. You can print your own summary of changes from that.

Otherwise, have a quick look at the what the '--style=summary' command is doing: https://github.com/larsyencken/csvdiff/blob/master/csvdiff/__init__.py#L159

You can pretty much do the same thing in your code. Does that help?

**Comment by GokulReddy** [comment]
Thank you..
That really works! Really having fun with this package.good work.

Regards,
Gokul

**Comment by larsyencken** [comment]
Thanks, glad you're enjoying it!
